# Generated by Django 3.2.9 on 2021-12-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0002_auto_20211129_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.DecimalField(decimal_places=0, max_digits=9)),
                ('income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditcard', to='UserAdmin.userprofile')),
            ],
        ),
    ]
