# Generated by Django 3.2.9 on 2021-12-03 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAdmin', '0003_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='account',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='Username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creditcard', to='auth.user'),
            preserve_default=False,
        ),
    ]
